# Generated by Django 4.1.2 on 2022-10-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifpi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(max_length=80, null=True)),
                ('name_user', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
