# Generated by Django 4.1.2 on 2022-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifpi', '0002_bets'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='concurso_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='bet',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='name_user',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
