# Generated by Django 4.1.2 on 2022-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ifpi', '0006_delete_bets_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_result', models.CharField(max_length=80, null=True)),
                ('last_date_update', models.DateField(auto_now=True, max_length=80, null=True)),
            ],
        ),
    ]
