# Generated by Django 4.1.2 on 2022-11-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifpi', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(max_length=40, null=True)),
                ('name_user', models.CharField(max_length=40, null=True)),
                ('concurso_id', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
